name = "ChainDyn"
uuid = "e2a1edfe-77c0-11e9-1bb8-6bbdf3172b25"
authors = ["Christian Dengler <c.dengler@tum.de>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
